### ISSUE TITLE
How to generate Result.json?

### ISSUE THREAD

**Issue by SamiurRahman1** [kevaldoshi17/NVIDIA_AICITY#3]
In the background modelling part, after running yolov3, we are suppsed to save it as result.json. Usually yolov3 outputs results as .txt file and it does not look like the result.json provided in the repo. Is there anything extra need to be done to get result.json file?

**Comment by kevaldoshi17** [comment]
You can save it in json format by running

./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -ext_output -dont_show -out result_seg2.json < names.txt -thresh 0.1

This should save the result in json format and will also save the bounding boxes coordinates.

**Comment by SamiurRahman1** [comment]
> You can save it in json format by running
> 
> ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -ext_output -dont_show -out result_seg2.json < names.txt -thresh 0.1
> 
> This should save the result in json format and will also save the bounding boxes coordinates.

Thank you so much for the reply. I just have one more question, 
"1. Run `python extract_frames.py` to extract frames from the videos with frequency set as 100."

What did you mean by frequency set as 100 and then again in segmentation map section - frequency set as 10?
Do i need to change Line 45(start_frame = 100) in extract_frames.py to 100 and 10?
Thanks

**Comment by SamiurRahman1** [comment]
> You can save it in json format by running
> 
> ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -ext_output -dont_show -out result_seg2.json < names.txt -thresh 0.1
> 
> This should save the result in json format and will also save the bounding boxes coordinates.

Another question arises. How am i giving the image files as input? i don't see any --source argument. Sorry if it is a stupid question. I am fairly new to yolo.

**Comment by SamiurRahman1** [comment]
> You can save it in json format by running
> 
> ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -ext_output -dont_show -out result_seg2.json < names.txt -thresh 0.1
> 
> This should save the result in json format and will also save the bounding boxes coordinates.

Sorry for being a nuisance. What is "names.txt" file in this case and how do i get/generate it?

**Comment by kevaldoshi17** [comment]
> > You can save it in json format by running
> > ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -ext_output -dont_show -out result_seg2.json < names.txt -thresh 0.1
> > This should save the result in json format and will also save the bounding boxes coordinates.
> 
> Thank you so much for the reply. I just have one more question,
> "1. Run `python extract_frames.py` to extract frames from the videos with frequency set as 100."
> 
> What did you mean by frequency set as 100 and then again in segmentation map section - frequency set as 10?
> Do i need to change Line 45(start_frame = 100) in extract_frames.py to 100 and 10?
> Thanks

**Comment by kevaldoshi17** [comment]
1) Apart from the change on line 45, you also need to change it on line 25 after uncommenting the section. The commented section is only required to be run once for extracting the frames for a given frequency. 

2-3. The file name.txt should contain the path to all the images that you want to run Yolo on. That is given as input to the detector and no --source command is required.

**Comment by SamiurRahman1** [comment]
Thank you so much for your help. :+1:  :) it works.

**Comment by SamiurRahman1** [comment]
Hello, small question. When i change the frequency set to 10 in Line 25,45 and 52, i get an error. Specially from Line 25. and only happens when the frequency value is changed from 100. This is the error i get:

`caputure videos
 10%|████▍                                       | 1/10 [01:14<11:11, 74.65s/it]
Traceback (most recent call last):
  File "extract_frames.py", line 31, in <module>
    cv2.imwrite(pic_path + str(c) + '.jpg', frame)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:715: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'`

**Comment by Mandroide** [comment]
> Hello, small question. When i change the frequency set to 10 in Line 25,45 and 52, i get an error. Specially from Line 25. and only happens when the frequency value is changed from 100. This is the error i get:
> 
> `caputure videos 10%|████▍ | 1/10 [01:14<11:11, 74.65s/it] Traceback (most recent call last): File "extract_frames.py", line 31, in <module> cv2.imwrite(pic_path + str(c) + '.jpg', frame) cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:715: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'`

Sorry for the late reply, this might have happened because the algorithm originally within the while loop had the order messy. This one should be resolved by #4.
